// Build-time codegen for the launcher exe.
//
// Walks the already-built dist/ tree and emits launcher/embedded.generated.ts:
// a module that statically imports every dist file `with { type: "file" }`.
// `bun build --compile` sees those static imports and bakes the file bytes into
// the single executable (Bun's native asset embedding — the same mechanism the
// spec's task 3 asks for, verified to work in a compiled binary). The runtime
// server (launcher/main.ts) maps a URL path to each embedded reference.
//
// Per-file embedding keeps the runtime simple and avoids any archive/unpack
// step. dist/ is small (~20 files) so the generated import list stays short.
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { relative, resolve, sep } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const DIST = resolve(ROOT, 'dist');
const OUT = resolve(import.meta.dir, 'embedded.generated.ts');

// Must stay in sync with `base` in vite.config.ts (the GitHub Pages sub-path).
// The built index.html and pyodideWorker reference every asset under this
// prefix, so the launcher serves dist/ at exactly the same path — the build
// output is reused byte-for-byte, unmodified.
const BASE_PATH = '/modbus_simple_logger/';

if (!existsSync(DIST)) {
  console.error('[generate-embed] dist/ not found — run `bun run build` first.');
  process.exit(1);
}

const files: string[] = [];
const walk = (dir: string) => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
};
walk(DIST);
files.sort();

const imports: string[] = [];
const entries: string[] = [];
files.forEach((full, i) => {
  const rel = relative(DIST, full).split(sep).join('/');
  // Import path is relative to this generated file (launcher/…), so dist/ is
  // one level up.
  const importPath = `../dist/${rel}`;
  const urlPath = BASE_PATH + rel;
  imports.push(`import a${i} from ${JSON.stringify(importPath)} with { type: 'file' };`);
  entries.push(`  ${JSON.stringify(urlPath)}: a${i},`);
});

const out = [
  '// AUTO-GENERATED by launcher/generate-embed.ts — DO NOT EDIT.',
  '// Regenerated on every `bun run launcher:dev` / `launcher:build`.',
  '// Gitignored: it references content-hashed dist filenames.',
  '',
  ...imports,
  '',
  `export const BASE_PATH = ${JSON.stringify(BASE_PATH)};`,
  '',
  'export const ASSETS: Record<string, string> = {',
  ...entries,
  '};',
  '',
].join('\n');

writeFileSync(OUT, out);
console.log(`[generate-embed] Embedded ${files.length} files from dist/ into ${relative(ROOT, OUT)}`);
